#!/bin/bash
# reset-audio.sh
# Script to reset ALSA, PulseAudio, and PipeWire on Ubuntu

SCARLETT_CARD_NAME_PATTERN="alsa_card.usb-Focusrite_Scarlett_*"
WIREPLUMBER_RULE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/wireplumber/main.lua.d"
WIREPLUMBER_RULE_FILE="$WIREPLUMBER_RULE_DIR/51-scarlett-soft-mixer.lua"

has_scarlett_device() {
    aplay -l 2>/dev/null | grep -qi 'Scarlett'
}

ensure_scarlett_soft_mixer_rule() {
    if ! has_scarlett_device; then
        echo "[*] No Scarlett device detected; skipping Scarlett WirePlumber rule."
        return
    fi

    if grep -Fq "$SCARLETT_CARD_NAME_PATTERN" "$WIREPLUMBER_RULE_FILE" 2>/dev/null &&
       grep -Fq '["api.alsa.soft-mixer"] = true' "$WIREPLUMBER_RULE_FILE" 2>/dev/null; then
        echo "[*] Scarlett WirePlumber soft-mixer rule already exists."
        return
    fi

    echo "[*] Installing Scarlett WirePlumber soft-mixer rule..."
    mkdir -p "$WIREPLUMBER_RULE_DIR"
    tee "$WIREPLUMBER_RULE_FILE" >/dev/null <<EOF
-- Generated by ~/dotfiles/restartaudio.sh.
-- Force software volume for the Scarlett; its ALSA hardware Master changes
-- numerically but does not provide useful audible volume control.
table.insert(alsa_monitor.rules, {
  matches = {
    {
      { "device.name", "matches", "$SCARLETT_CARD_NAME_PATTERN" },
    },
  },
  apply_properties = {
    ["api.alsa.soft-mixer"] = true,
  },
})
EOF
}

ensure_scarlett_soft_mixer_rule

echo "[*] Stopping PipeWire and related services..."
systemctl --user stop pipewire.service pipewire-pulse.service wireplumber.service

echo "[*] Killing leftover audio processes..."
killall -q pipewire pipewire-pulse wireplumber pulseaudio 2>/dev/null

echo "[*] Unloading ALSA modules..."
sudo alsa force-unload 2>/dev/null
sudo alsa force-reload

echo "[*] Clearing PulseAudio state..."
rm -rf ~/.config/pulse
rm -rf ~/.pulse*

echo "[*] Restarting PipeWire services..."
systemctl --user start pipewire.service pipewire-pulse.service wireplumber.service

echo "[*] Restarting ALSA..."
sudo alsa force-reload

echo "[*] Done. You may need to log out and back in if audio devices still don’t appear."
